ServerEvents.recipes(event=>{
    event.custom(
       {"type":"mekanism:oxidizing","input":{"count":1,"item":"minecraft:nether_star"},"output":{"amount":100,"id":"ccb:netherstar_gas"}}
    )
    event.custom(
       {"type":"mekanism:oxidizing","input":{"count":1,"item":"allthetweaks:nether_star_block"},"output":{"amount":900,"id":"ccb:netherstar_gas"}}
    )
    event.custom(
       {"type":"mekanism:oxidizing","input":{"count":1,"item":'ae2:singularity'},"output":{"amount":10,"id":"ccb:singularity_gas"}}
    )
    event.custom(
       {"type":"mekanism:oxidizing","input":{"count":1,"item":'ae2omnicells:singularity_block'},"output":{"amount":90,"id":"ccb:singularity_gas"}}
    )
})