ServerEvents.recipes(event =>{
event.recipes.occultism.ritual(
'ccb:antimatter_soup',
[//输出物品
'mekanism:pellet_antimatter',
'ae2lt:overload_alloy',
'enderio_evolution:stellar_alloy_block',
'ends_delight:fried_dragon_egg',
'arsdelight:grilled_wilden_meat',
'arsdelight:grilled_chimera_meat',
'farmersdelight:rotten_tomato'
],
'occultism:eldritch_chalice',//仪式核心输入物品（放在黄金献祭之碗上的）
'occultism:marid_cooking_ritual'
    ).dummy("ccb:cook_ritual_misc").useItem("minecraft:egg")
    event.recipes.occultism.ritual(
'ccb:uumatter_soup',
[//输出物品
'arsdelight:wilden_meat',
'arsdelight:chimera_meat',
'ae2lt:overload_alloy_blank',
'farmersdelight:tomato',
'ends_delight:liquid_dragon_egg',
'allthemodium:unobtainium_block',
'mekmm:uu_matter'
],
'occultism:celestial_chalice',//仪式核心输入物品（放在黄金献祭之碗上的）
'occultism:marid_cooking_ritual'
    ).dummy("ccb:cook_ritual_misc").useItem("minecraft:egg")
    event.recipes.occultism.ritual(
'avaritia:ultimate_stew',
[//输出物品
'arsdelight:wilden_salad',
'arsdelight:arch_soup',
'arsdelight:horn_roll',
'arsdelight:arch_sauce',
'ends_delight:end_mixed_salad',
'ends_delight:assorted_salad',
'farmersdelight:cooked_rice',
'farmersdelight:stuffed_potato',
'farmersdelight:fruit_salad',
'farmersdelight:nether_salad',
'farmersdelight:cabbage_rolls',
'farmersdelight:fried_rice',
'farmersdelight:pumpkin_soup',
'farmersdelight:onion_soup',
'farmersdelight:mushroom_rice',
'farmersdelight:vegetable_noodles',
'farmersdelight:ratatouille',
'farmersdelight:stuffed_pumpkin_block',
'farmersdelight:stuffed_pumpkin',
'farmersdelight:gleaming_salad_block',
'farmersdelight:gleaming_salad',
'ends_delight:stuffed_rice_cake',
'ends_delight:chorus_flower_pie',
'ends_delight:chorus_cookie',
'arsdelight:mendosteen_jelly',
'arsdelight:bastion_jelly',
'arsdelight:bombegrante_jelly',
'arsdelight:frostaya_jelly',
'arsdelight:source_berry_jelly',
'arsdelight:mendosteen_pie',
'arsdelight:bastion_pie',
'arsdelight:bombegrante_pie',
'arsdelight:frostaya_pie',
'arsdelight:mendosteen_pie_slice',
'arsdelight:bastion_pie_slice',
'arsdelight:bombegrante_pie_slice',
'arsdelight:frostaya_pie_slice',
'farmersdelight:apple_pie',
'farmersdelight:sweet_berry_cheesecake',
'farmersdelight:chocolate_pie',
'farmersdelight:sweet_berry_cookie',
'arsdelight:source_berry_cookie',
'arsdelight:source_berry_cupcake',
'farmersdelight:honey_cookie',
'farmersdelight:sweet_berry_cheesecake_slice',
'minecraft:pumpkin_pie',
'farmersdelight:pumpkin_pie_slice',
'farmersdelight:apple_pie_slice'
],
'ccb:antimatter_soup',//仪式核心输入物品（放在黄金献祭之碗上的）
'occultism:marid_cooking_ritual'
    ).dummy("avaritia:ultimate_stew")
        event.recipes.occultism.ritual(
'avaritia:cosmic_meatballs',
[//输出物品
'arsdelight:honey_glazed_chimera',
'arsdelight:wilden_skewer',
'arsdelight:grilled_wilden_skewer',
'arsdelight:chimera_skewer',
'arsdelight:grilled_chimera_skewer',
'arsdelight:bowl_of_honey_glazed_chimera',
'arsdelight:mendosteen_chicken',
'arsdelight:bastion_pork',
'arsdelight:bombegrante_steak',
'arsdelight:frostaya_mutton',
'farmersdelight:barbecue_stick',
'farmersdelight:egg_sandwich',
'farmersdelight:chicken_sandwich',
'farmersdelight:hamburger',
'farmersdelight:bacon_sandwich',
'farmersdelight:mutton_wrap',
'farmersdelight:dumplings',
'farmersdelight:salmon_roll',
'farmersdelight:cod_roll',
'farmersdelight:kelp_roll',
'farmersdelight:kelp_roll_slice',
'farmersdelight:bone_broth',
'farmersdelight:beef_stew',
'farmersdelight:chicken_soup',
'farmersdelight:fish_stew',
'farmersdelight:baked_cod_stew',
'farmersdelight:bacon_and_eggs',
'farmersdelight:pasta_with_meatballs',
'farmersdelight:pasta_with_mutton_chop',
'farmersdelight:pasta_with_mutton_chop',
'farmersdelight:steak_and_potatoes',
'farmersdelight:squid_ink_pasta',
'farmersdelight:grilled_salmon',
'farmersdelight:roast_chicken_block',
'farmersdelight:honey_glazed_ham_block',
'farmersdelight:shepherds_pie_block',
'farmersdelight:rice_roll_medley_block',
'ends_delight:shulker_omelette',
'ends_delight:ender_congee',
'ends_delight:ender_bamboo_rice',
'ends_delight:ender_congee',
'ends_delight:shulker_soup',
'ends_delight:ender_noodle',
'ends_delight:enderman_gristle_stew',
'ends_delight:stir_fried_shulker_meat',
'ends_delight:roasted_dragon_steak',
'ends_delight:end_barbecue_stick',
'ends_delight:dragon_leg_with_sauce_block',
'ends_delight:steamed_dragon_egg_block',
'ends_delight:dragon_meat_stew',
'ends_delight:grilled_shulker_block'
],
'ccb:uumatter_soup',//仪式核心输入物品（放在黄金献祭之碗上的）
'occultism:marid_cooking_ritual'
    ).dummy('avaritia:cosmic_meatballs')
    event.recipes.occultism.ritual(
'hostilenetworks:data_model[hostilenetworks:data_model="hostilenetworks:block/iesnium_ore"]',
[//输出物品
'occultengineering:combined_goggles',
'occultism:infused_pickaxe',
'occultism:divination_rod',
'occultism:crushed_blue_ice',
'occultism:stable_wormhole'
],
'hostilenetworks:blank_data_model',
'occultism:craft_djinni'
    ).dummy('occultism:ritual_dummy/custom_ritual_craft')
        event.recipes.occultism.ritual(
'ccb:life_crystal',
[//输出物品
'projecte:life_stone',
'mob_grinding_utils:entity_spawner',
'occultism:vitality_compass',
'occultism:cursed_honey',
'occultism:demonic_meat',
'extendedcrafting:singularity[extendedcrafting:singularity_id="extendedcrafting:blood_upgrade_orb"]',
'jdte:life_synthesis_vat',
'occultism:spawn_egg/familiar_fairy'
],
'apotheosis:gem[apotheosis:gem="apotheosis:the_nether/blood_lord",apotheosis:purity="perfect"]',
"occultism:contact_eldritch_spirit"
    ).dummy('occultism:ritual_dummy/custom_ritual_craft')
    
    
});
