ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.alien_chicken(16, 20)
        .itemIn("chicken_roost:c_certusquartz")
        .itemIn('justdynathings:echoing_budding_certus')
        .itemIn('128x ae2:charged_certus_quartz_crystal')
        .itemIn('ae2:flawless_budding_quartz')
        .fluidIn("64000x minecraft:water")
        .itemOut('chicken_roost:c_chargedcertus');
    event.recipes.modern_industrialization.alien_chicken(16, 20)
        .itemIn("chicken_roost:c_chargedcertus")
        .itemIn('chicken_roost:c_quartz')
        .itemIn('64x ae2:fluix_block')
        .itemIn('chicken_roost:c_redstone')
        .fluidIn("64000x minecraft:water")
        .itemOut('chicken_roost:c_fluixcrystal');
    event.recipes.modern_industrialization.alien_chicken(16, 20)
        .itemIn('chicken_roost:c_cobble')
        .itemIn('64x ae2cs:purified_meteor_crystal')
        .fluidIn("64000x minecraft:water")
        .itemOut('chicken_roost:c_skystone');
    event.recipes.modern_industrialization.alien_chicken(16, 20)
        .itemIn('chicken_roost:c_vanilla')
        .itemIn('extendedae:void_cell')
        .itemIn('64x ae2:fluix_pearl')
        .itemIn('extendedae:infinity_cobblestone_cell')
        .fluidIn("64000x minecraft:lava")
        .itemOut('chicken_roost:c_singularity');
    event.recipes.modern_industrialization.alien_chicken(16, 20)
        .itemIn('chicken_roost:c_fluixcrystal')
        .itemIn('64x extendedae:entro_seed')
        .itemIn('64x extendedae:entro_block')
        .itemIn('justdynathings:echoing_budding_entro')
        .fluidIn("64000x minecraft:water")
        .itemOut('chicken_roost:c_entrocrystal');
    event.recipes.modern_industrialization.alien_chicken(16, 20)
        .itemIn('chicken_roost:c_singularity')
        .itemIn('chicken_roost:c_copper')
        .itemIn('64x ae2cs:purified_quantum_crystal')
        .itemIn('64x advanced_ae:quantum_alloy_block')
        .fluidIn("8000x advanced_ae:quantum_infusion_source")
        .itemOut('chicken_roost:c_quantumalloy');
    event.recipes.modern_industrialization.alien_chicken(16, 20)
        .itemIn('chicken_roost:c_iron')
        .itemIn('64x allthetweaks:ender_pearl_block')
        .itemIn('64x ae2cs:purified_ender_quartz')
        .itemIn('64x ae2:quartz_block')
        .fluidIn("64000x minecraft:water")
        .itemOut('chicken_roost:c_enderium');
    event.recipes.modern_industrialization.alien_chicken(32, 20)
        .itemIn('chicken_roost:c_certusquartz')
        .itemIn('256x ae2lt:pigmee_fumo')
        .itemIn('64x ae2lt:overload_crystal')
        .itemIn('ae2lt:flawless_budding_overload_crystal')
        .fluidIn("1000x data_energistics:data_corrosion_liquid")
        .itemOut('chicken_roost:c_overloadcrystal');
});
