ServerEvents.recipes(event => {
event.recipes.modern_industrialization.alien_chicken(16, 20)
.itemIn("chicken_roost:c_certusquartz")
.itemIn('justdynathings:echoing_budding_certus')
.itemIn('128x ae2:charged_certus_quartz_crystal')
.itemIn('ae2:flawless_budding_quartz')
.itemOut('chicken_roost:c_chargedcertus')
.fluidIn("64000x minecraft:water")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.alien_chicken(16, 20)
.itemIn("chicken_roost:c_chargedcertus")
.itemIn('chicken_roost:c_quartz')
.itemIn('64x ae2:fluix_block')
.itemIn('chicken_roost:c_redstone')
.itemOut('chicken_roost:c_fluixcrystal')
.fluidIn("64000x minecraft:water")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.alien_chicken(16, 20)
.itemIn('chicken_roost:c_cobble')
.itemIn('64x ae2cs:purified_meteor_crystal')
.itemOut('chicken_roost:c_skystone')
.fluidIn("64000x minecraft:water")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.alien_chicken(16, 20)
.itemIn('chicken_roost:c_vanilla')
.itemIn('extendedae:void_cell')
.itemIn('64x ae2:fluix_pearl')
.itemIn('extendedae:infinity_cobblestone_cell')
.itemOut('chicken_roost:c_singularity')
.fluidIn("64000x minecraft:lava")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.alien_chicken(16, 20)
.itemIn('chicken_roost:c_fluixcrystal')
.itemIn('64x extendedae:entro_seed')
.itemIn('64x extendedae:entro_block')
.itemIn('justdynathings:echoing_budding_entro')
.itemOut('chicken_roost:c_entrocrystal')
.fluidIn("64000x minecraft:water")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.alien_chicken(16, 20)
.itemIn('chicken_roost:c_singularity')
.itemIn('chicken_roost:c_copper')
.itemIn('64x ae2cs:purified_quantum_crystal')
.itemIn('64x advanced_ae:quantum_alloy_block')
.itemOut('chicken_roost:c_quantumalloy')
.fluidIn("8000x advanced_ae:quantum_infusion_source")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.alien_chicken(16, 20)
.itemIn('chicken_roost:c_iron')
.itemIn('64x allthetweaks:ender_pearl_block')
.itemIn('64x ae2cs:purified_ender_quartz')
.itemIn('64x ae2:quartz_block')
.itemOut('chicken_roost:c_enderium')
.fluidIn("64000x minecraft:water")
event.recipes.modern_industrialization.alien_chicken(32, 20)
.itemIn('chicken_roost:c_certusquartz')
.itemIn('256x ae2lt:pigmee_fumo')
.itemIn('64x ae2lt:overload_crystal')
.itemIn('ae2lt:flawless_budding_overload_crystal')
.itemOut('chicken_roost:c_overloadcrystal')
.fluidIn("1000x data_energistics:data_corrosion_liquid")
})