ServerEvents.recipes(event => {
event.recipes.modern_industrialization.create_chicken(128, 400)
.itemIn('2x create:mechanical_press')
.itemIn('#c:dusts/obsidian')
.itemOut('create:sturdy_sheet')
.fluidIn("1000x minecraft:lava")
event.recipes.modern_industrialization.create_chicken(128, 400)
.itemIn('create:mechanical_press')
.itemIn('chicken_roost:c_zinc')
.itemIn('minecraft:ender_eye')
.itemOut('minecraft:end_portal_frame')
.fluidIn("1000x create_dragons_plus:white_dye")
event.recipes.modern_industrialization.create_chicken(128, 400)
.itemIn('minecraft:andesite_slab')
.itemIn('2x minecraft:iron_nugget')
.itemIn('create:mechanical_press')
.itemOut('create:track')
event.recipes.modern_industrialization.create_chicken(128, 400)
.itemIn('#c:plates/gold')
.itemIn('10x minecraft:iron_nugget')
.itemIn('10x create:cogwheel')
.itemIn('10x create:cogwheel')
.itemOut('create:precision_mechanism')
event.recipes.modern_industrialization.create_chicken(128, 400)
.itemIn('#c:plates/gold')
.itemIn('3x create:electron_tube')
.itemIn('3x minecraft:redstone')
.itemIn('3x create:mechanical_press')
.itemOut('create_connected:control_chip')
event.recipes.modern_industrialization.create_chicken(32, 100)
.itemIn('#c:stripped_logs')
.itemIn('create:andesite_alloy')
.itemOut('create:andesite_casing')
event.recipes.modern_industrialization.create_chicken(32, 100)
.itemIn('#c:stripped_logs')
.itemIn('minecraft:copper_ingot')
.itemOut('create:copper_casing')
event.recipes.modern_industrialization.create_chicken(32, 100)
.itemIn('#c:stripped_logs')
.itemIn('create:brass_ingot')
.itemOut('create:brass_casing')
event.recipes.modern_industrialization.create_chicken(32, 100)
.itemIn('create:brass_casing')
.itemIn('create:sturdy_sheet')
.itemOut('create:railway_casing')
})