ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('3x minecraft:lightning_rod')
.itemIn('minecraft:heart_of_the_sea')
.itemIn('ars_nouveau:air_essence')
.itemOut('ars_nouveau:glyph_lightning')
.fluidIn("1000x #c:experience")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('ars_nouveau:glyph_lightning')
.itemIn('8x minecraft:glass_bottle')
.itemOut('8x irons_spellbooks:lightning_bottle')
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('ars_nouveau:thread_life_drain')
.itemIn('8x minecraft:glass_bottle')
.itemOut('8x irons_spellbooks:blood_vial')
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('minecraft:potion[potion_contents={potion:"minecraft:water"}]')
.itemIn('minecraft:coal')
.itemOut('irons_spellbooks:common_ink')
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('4x irons_spellbooks:common_ink')
.itemIn(' minecraft:copper_ingot')
.itemOut('irons_spellbooks:uncommon_ink')
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('4x irons_spellbooks:uncommon_ink')
.itemIn(' minecraft:iron_ingot')
.itemOut('irons_spellbooks:rare_ink')
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('4x irons_spellbooks:rare_ink')
.itemIn(' minecraft:gold_ingot')
.itemOut('irons_spellbooks:epic_ink')
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('4x irons_spellbooks:epic_ink')
.itemIn('minecraft:amethyst_shard')
.itemOut('irons_spellbooks:legendary_ink')
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('minecraft:paper')
.itemIn('#c:dusts/emerald')
.itemIn('2x #c:dusts/iron')
.itemIn('mahoutsukai:dagger',0)
.itemOut('mahoutsukai:scroll_boundary_drain_life')
.fluidIn("1000x irons_spellbooks:blood")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 800)
.itemIn('chicken_roost:c_red')
.itemIn('64x irons_spellbooks:legendary_ink')
.itemIn('64x mahoutsukai:scroll_boundary_drain_life')
.itemOut('chicken_roost:c_blood')
.fluidIn("64000x irons_spellbooks:blood")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('#c:dusts/emerald')
.itemIn('#c:dusts/diamond')
.itemIn('#c:dusts/gold')
.itemIn('mahoutsukai:dagger',0)
.itemOut('mahoutsukai:scroll_gandr')
.fluidIn("1000x irons_spellbooks:blood")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('#c:dusts/emerald')
.itemIn('#c:dusts/diamond')
.itemIn('#c:dusts/gold')
.itemIn('mahoutsukai:dagger',0)
.itemOut('mahoutsukai:scroll_gandr')
.fluidIn("1000x irons_spellbooks:blood")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('#c:dusts/emerald')
.itemIn('#c:dusts/iron')
.itemIn('#c:dusts/gold')
.itemIn('mahoutsukai:dagger',0)
.itemOut('mahoutsukai:scroll_geas')
.fluidIn("1000x irons_spellbooks:blood")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 800)
.itemIn('minecraft:echo_shard')
.itemIn('minecraft:breeze_rod')
.fluidOut('1000x irons_spellbooks:timeless_slurry')
.fluidIn("1000x minecraft:water")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('minecraft:paper')
.itemIn('mahoutsukai:scroll_geas')
.itemIn('mahoutsukai:scroll_gandr')
.itemIn('allthemodium:ancient_soulberries')
.itemOut('irons_spellbooks:ancient_knowledge_fragment')
.fluidIn("1000x irons_spellbooks:timeless_slurry")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('2x minecraft:prismarine_shard')
.itemIn('ars_nouveau:conjuration_essence')
.itemIn('minecraft:totem_of_undying')
.itemOut('ars_nouveau:glyph_fangs')
.fluidIn("1000x #c:experience")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('ars_nouveau:glyph_fangs')
.itemIn('8x minecraft:blue_ice')
.itemOut('8x irons_spellbooks:icy_fang')
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 400)
.itemIn('1024x minecraft:blue_ice')
.itemOut('irons_spellbooks:permafrost_shard')
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.magic_chicken(32, 800)
.itemIn('irons_spellbooks:icy_fang')
.fluidOut('1000x irons_spellbooks:ice_venom')
.fluidIn("1000x minecraft:water")
})

