ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.mixer(64, 1200)
        .fluidIn("1000x minecraft:milk")
        .fluidIn("10000x modern_industrialization:heavy_water")
        .itemOut('fluidsneo:fluid_cow_spawn_egg[fluidsneo:fluid_type="modern_industrialization:deuterium"]');
    event.recipes.modern_industrialization.mixer(256, 1200)
        .itemIn('modern_industrialization:nuclear_reactor')
        .fluidIn("1000x minecraft:milk")
        .fluidIn("10000x modern_industrialization:high_pressure_heavy_water")
        .itemOut('fluidsneo:fluid_cow_spawn_egg[fluidsneo:fluid_type="modern_industrialization:tritium"]');
        event.recipes.modern_industrialization.mixer(1024, 800)
        .itemIn('draconicevolution:small_chaos_frag')
        .fluidIn("1x justdirethings:portal_fluid_source")
        .fluidIn("1x ccb:end_fluid")
        .fluidOut("1x ccb:chaotic_polarization_fluid")
        .customCondition('end_coordinates_over_10000')
         event.recipes.modern_industrialization.mixer(1024, 200)
       .itemIn('draconicevolution:medium_chaos_frag')
         .fluidIn("10x justdirethings:portal_fluid_source")
        .fluidIn("10x ccb:end_fluid")
         .fluidOut("10x ccb:chaotic_polarization_fluid")
        .customCondition('end_coordinates_over_10000')
        event.recipes.modern_industrialization.mixer(1024, 400)
       .itemIn('draconicevolution:large_chaos_frag')
        .fluidIn("100x justdirethings:portal_fluid_source")
        .fluidIn("100x ccb:end_fluid")
         .fluidOut("100x ccb:chaotic_polarization_fluid")
        .customCondition('end_coordinates_over_10000')
        event.recipes.modern_industrialization.mixer(1024, 800)
       .itemIn('draconicevolution:chaos_shard')
        .fluidIn("1000x justdirethings:portal_fluid_source")
        .fluidIn("1000x ccb:end_fluid")
        .fluidOut("1000x ccb:chaotic_polarization_fluid")
        .customCondition('end_coordinates_over_10000')   
});
