ServerEvents.recipes(event => {
    event.recipes.modern_mekanistics.niuniu_brand_cooking_machine(32, 20)
        .itemIn('minecraft:glass_bottle')
        .itemIn('mekanism:hdpe_stick')
        .itemIn('#c:raw_blocks')
        .itemIn('mekmm:advanced_electrolysis_core')
        .chemicalIn("100x mekanism:oxygen")
        .chemicalIn("100x mekanism:hydrogen_chloride")
        .chemicalIn("100x mekanism:sulfuric_acid")
        .chemicalIn("100x mekanism:steam")
        .itemOut("ccb:mineral_processing_molecular_cuisine");
    event.recipes.modern_mekanistics.niuniu_brand_cooking_machine(128, 20)
        .itemIn('mekanism:qio_drive_array', 0)
        .itemIn('mekanism:superheating_element')
        .itemIn('farmersdelight:wheat_dough')
        .itemIn('mekanism:qio_drive_base')
        .chemicalIn("100x mekanism:bio")
        .chemicalIn("100x mekanism:carbon")
        .itemOut('ccb:qio_special_toast_bread');
    event.recipes.modern_mekanistics.niuniu_brand_cooking_machine(32, 20)
        .itemIn('mekanism:alloy_infused')
        .itemIn('mekanism:alloy_reinforced')
        .itemIn('mekanism_extras:alloy_radiance')
        .itemIn('mekanism:block_refined_obsidian')
        .chemicalIn("1000x mekanism:fungi")
        .itemOut('ccb:bacterial_juice_ranbow');
    event.recipes.modern_mekanistics.niuniu_brand_cooking_machine(64, 200)
        .itemIn('256x farmersdelight:minced_beef')
        .itemIn('modern_industrialization:ultradense_metal_ball')
        .itemIn('ars_elemental:flashpine_pod')
        .itemIn('alltheores:salt')
        .chemicalIn("1000x mekanismgenerators:tritium")
        .chemicalIn("1000x mekanismgenerators:deuterium")
        .itemOut('ccb:beef_balls');
    event.recipes.modern_mekanistics.niuniu_brand_cooking_machine(64, 200)
        .itemIn('allthemodium:allthemodium_ingot')
        .itemIn('allthemodium:vibranium_ingot')
        .itemIn('allthemodium:unobtainium_ingot')
        .itemIn('allthemodium:piglich_heart_block')
        .chemicalIn("64000x ccb:singularity_gas")
        .chemicalIn("8000x ccb:netherstar_gas")
        .itemOut('ccb:atm_vibranium_unobtainium_alloy_ingot');
    event.recipes.modern_mekanistics.niuniu_brand_cooking_machine(256, 200)
        .itemIn('avaritia:star_fuel')
        .itemIn('oritech:still_sulfuric_acid_bucket')
        .itemIn('ifeu:liquid_malic_acid_bucket')
        .itemIn('pneumaticcraft:etching_acid_bucket')
        .chemicalIn("8000x mekanism:sulfuric_acid")
        .chemicalIn("8000x mekanism:hydrofluoric_acid")
        .itemOut('ccb:star_acid');
    event.recipes.modern_mekanistics.niuniu_brand_cooking_machine(256, 200)
        .itemIn('ae2omnicells:spent_nuclear_waste_cell')
        .itemIn('64x actuallyadditions:coffee_beans')
        .itemIn('pneumaticcraft:yeast_culture_bucket')
        .chemicalIn("1024000x mekanism:spent_nuclear_waste")
        .itemOut('ccb:exhaust_nuclear_waste_sauce');
});
