ServerEvents.recipes(event => {
event.recipes.modern_industrialization.time_chicken(32, 800)
.itemIn('chicken_roost:c_iron')
.itemIn('64x justdirethings:coal_t1')
.itemIn('64x justdirethings:ferricore_ingot')
.itemIn('justdynathings:charged_primogel_goo')
.itemOut('chicken_roost:c_ferricore')
.fluidIn("6400x justdirethings:polymorphic_fluid_source")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.time_chicken(64, 800)
.itemIn('chicken_roost:c_gold')
.itemIn('justdirethings:gooblock_tier2')
.itemIn('64x justdirethings:blazegold_ingot')
.itemIn('justdynathings:charged_blazebloom_goo')
.itemOut('chicken_roost:c_blazegold')
.fluidIn("6400x justdirethings:refined_t2_fluid_source")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.time_chicken(128, 800)
.itemIn('chicken_roost:c_diamond')
.itemIn('justdirethings:gooblock_tier3')
.itemIn('64x justdirethings:celestigem')
.itemIn('justdynathings:charged_voidshimmer_goo')
.itemOut('chicken_roost:c_celestigem')
.fluidIn("6400x justdirethings:refined_t3_fluid_source")
})
ServerEvents.recipes(event => {
event.recipes.modern_industrialization.time_chicken(256, 800)
.itemIn('chicken_roost:c_netherite')
.itemIn('justdirethings:gooblock_tier4')
.itemIn('64x justdirethings:eclipsealloy_ingot')
.itemIn('justdynathings:charged_shadowpulse_goo')
.itemOut('chicken_roost:c_eclipsealloy')
.fluidIn("6400x justdirethings:refined_t4_fluid_source")
})