global.COW_TRANSMUTE_RULES = [
  { item: "minecraft:oak_leaves", fluid: "minecraft:water" },
  { item: "minecraft:cobblestone", fluid: "minecraft:lava" },
  { item: "allthemodium:allthemodium_block", fluid: "allthemodium:molten_allthemodium" },
  { item: "allthemodium:vibranium_block", fluid: "allthemodium:molten_vibranium" },
  { item: "allthemodium:unobtainium_block", fluid: "allthemodium:molten_unobtainium" },
  { item: 'jdte:time_fluid_catalyst', fluid: "justdirethings:time_fluid_source" },
  { item: 'justdirethings:polymorphic_catalyst', fluid: "justdirethings:polymorphic_fluid_source" },
  { item: 'modern_industrialization:aluminum_drill', fluid: "modern_industrialization:crude_oil" },
  { item: 'industrialforegoing:dryrubber', fluid: "industrialforegoing:latex" },
  { item: 'industrialforegoing:sewer', fluid: "industrialforegoing:sewage" },
  { item: 'industrialforegoing:bioreactor', fluid: "industrialforegoing:biofuel" },
  { item: 'industrialforegoing:pink_slime_block', fluid: "industrialforegoing:pink_slime" },
  { item: 'ifeu:fermenter', fluid: "industrialforegoing:sludge" },
  { item: 'jdte:wither_spawn_egg', fluid: "industrialforegoing:ether_gas" },
  { item: 'modern_industrialization:air_intake', fluid: "modern_industrialization:liquid_air" },
  { item: 'modern_industrialization:heat_exchanger', fluid: "modern_industrialization:cryofluid" },
  { item: 'ifeu:apple_core', fluid: "ifeu:liquid_malic_acid" },
  { item: 'ars_nouveau:source_gem_block', fluid: "sauce:source_fluid" },
  { item: 'mekanism:brine_bucket', fluid: "mekanism:sodium" },
  { item: 'mekanism:sodium_bucket', fluid: "mekanism:superheated_sodium" },
  { item: 'mekanism_extras:naquadah_reactor_controller', fluid: "mekanism_extras:polonium_containing_solution" },
  { item: 'allthetweaks:ender_pearl_block', fluid: "data_energistics:ender" },
  { item: 'ifeu:dragon_star_block', fluid: "ifeu:dragon_star_essence" },
  { item: 'neoecoae:cryotheum_crystal', fluid: "neoecoae:cryotheum_solution" },
  { item: 'occultism:otherworld_essence', fluid: "occultengineering:spirit_solution" }
]
