AvaritiaEvents.singularity(event=>{
event.register("avaritia:dragon_star_essence_singularity",s=>{
s
.setDisplayName("singularity.avaritia.dragon_star_essence")
.setColors(0xfbbf24,0xf59e0b)
.setIngredient(Ingredient.of("ifeu:dragon_star_essence_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
