AvaritiaEvents.singularity(event=>{
event.register("avaritia:fusion_fuel_singularity",s=>{
s
.setDisplayName("singularity.avaritia.fusion_fuel")
.setColors(0xef4444,0xf97316)
.setIngredient(Ingredient.of("mekanismgenerators:fusion_fuel_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
