AvaritiaEvents.singularity(event=>{
event.register("avaritia:latex_singularity",s=>{
s
.setDisplayName("singularity.avaritia.latex")
.setColors(0xf5f5f4,0xe7e5e4)
.setIngredient(Ingredient.of("industrialforegoing:latex_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
