AvaritiaEvents.singularity(event=>{
event.register("avaritia:lava_singularity",s=>{
s
.setDisplayName("singularity.avaritia.lava")
.setColors(0xef4444,0xf97316)
.setIngredient(Ingredient.of("minecraft:lava_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
