AvaritiaEvents.singularity(event=>{
event.register("avaritia:liquid_dragon_breath_singularity",s=>{
s
.setDisplayName("singularity.avaritia.liquid_dragon_breath")
.setColors(0xd946ef,0xc026d3)
.setIngredient(Ingredient.of("ifeu:liquid_dragon_breath_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
