AvaritiaEvents.singularity(event=>{
event.register("avaritia:liquid_air_singularity",s=>{
s
.setDisplayName("singularity.avaritia.liquid_air")
.setColors(0x93c5fd,0xbfdbfe)
.setIngredient(Ingredient.of("modern_industrialization:liquid_air_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
