AvaritiaEvents.singularity(event=>{
event.register("avaritia:lubricant_singularity",s=>{
s
.setDisplayName("singularity.avaritia.lubricant")
.setColors(0xfbbf24,0xf59e0b)
.setIngredient(Ingredient.of("modern_industrialization:lubricant_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
