AvaritiaEvents.singularity(event=>{
event.register("avaritia:molten_unobtainium_singularity",s=>{
s
.setDisplayName("singularity.avaritia.molten_unobtainium")
.setColors(0x6366f1,0x4f46e5)
.setIngredient(Ingredient.of("allthemodium:molten_unobtainium_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
