AvaritiaEvents.singularity(event=>{
event.register("avaritia:molten_vibranium_singularity",s=>{
s
.setDisplayName("singularity.avaritia.molten_vibranium")
.setColors(0xa855f7,0x7c3aed)
.setIngredient(Ingredient.of("allthemodium:molten_vibranium_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
