AvaritiaEvents.singularity(event=>{
event.register("avaritia:sludge_singularity",s=>{
s
.setDisplayName("singularity.avaritia.sludge")
.setColors(0x44403c,0x292524)
.setIngredient(Ingredient.of("industrialforegoing:sludge_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
