AvaritiaEvents.singularity(event=>{
event.register("avaritia:source_fluid_singularity",s=>{
s
.setDisplayName("singularity.avaritia.source_fluid")
.setColors(0xa78bfa,0x8b5cf6)
.setIngredient(Ingredient.of("sauce:source_fluid_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
