AvaritiaEvents.singularity(event=>{
event.register("avaritia:spirit_solution_singularity",s=>{
s
.setDisplayName("singularity.avaritia.spirit_solution")
.setColors(0xc084fc,0xa855f7)
.setIngredient(Ingredient.of("occultengineering:spirit_solution_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
