AvaritiaEvents.singularity(event=>{
event.register("avaritia:sulfuric_acid_singularity",s=>{
s
.setDisplayName("singularity.avaritia.sulfuric_acid")
.setColors(0xeab308,0xca8a04)
.setIngredient(Ingredient.of("mekanism:sulfuric_acid_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
