AvaritiaEvents.singularity(event=>{
event.register("avaritia:superheated_sodium_singularity",s=>{
s
.setDisplayName("singularity.avaritia.superheated_sodium")
.setColors(0xf97316,0xea580c)
.setIngredient(Ingredient.of("mekanism:superheated_sodium_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
