AvaritiaEvents.singularity(event=>{
event.register("avaritia:tritium_singularity",s=>{
s
.setDisplayName("singularity.avaritia.tritium")
.setColors(0x93c5fd,0x818cf8)
.setIngredient(Ingredient.of("modern_industrialization:tritium_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
