AvaritiaEvents.singularity(event=>{
event.register("avaritia:uu_matter_singularity",s=>{
s
.setDisplayName("singularity.avaritia.uu_matter")
.setColors(0xc084fc,0xa855f7)
.setIngredient(Ingredient.of("modern_industrialization:uu_matter_bucket"))
.setEnabled(true)
.setRecipeDisabled(true)
})
})
